#
# Deploy OSPF routing in a WAN fabric
#
---
- name: Deploy OSPF configurations
  hosts: all
  vars:
    configs: "{{inventory_dir}}/configs"
  tasks:
  - include_vars: "{{ inventory_dir }}/nodes.yml"
  - ios_config:
      src: "{{configs}}/{{inventory_hostname}}.ospf.cfg"
    register: changes
    check_mode: yes
  - copy:
      content: |
        {% if ansible_check_mode %}
        === Running in check mode, configuration was not changed ===
        {% endif %}
        {% for line in changes.commands|default([]) %}
        {{ line }}
        {% endfor %}
      dest: "{{configs}}/{{inventory_hostname}}_changes.txt"
    changed_when: false
  - fail: msg="Too many changes on {{inventory_hostname}}, aborting"
    when: |
      changes.commands is defined and
      changes.commands|length > 10 and 
      force is not defined
  - ios_config:
      src: "{{configs}}/{{inventory_hostname}}.ospf.cfg"
    when: not ansible_check_mode